# Generated by Django 3.0.3 on 2020-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='0567817018', max_length=13),
            preserve_default=False,
        ),
    ]
