# Generated by Django 3.0.3 on 2020-04-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200423_1457'),
        ('users', '0003_auto_20200423_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bloodCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.BloodCenter'),
        ),
    ]
