# Generated by Django 3.0.3 on 2020-04-22 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCenter',
            fields=[
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('phone_num', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date-time created')),
                ('blood_center_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BloodCenter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='GetName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.History')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BloodCenter')),
            ],
        ),
    ]
