# Generated by Django 3.0.3 on 2020-05-02 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('phone_num', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('blood_type', models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')])),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date-time created')),
                ('blood_center_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BloodCenter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Donor')),
            ],
            options={
                'unique_together': {('date', 'user_id')},
            },
        ),
    ]
