# Generated by Django 3.0.3 on 2020-04-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='blood_center_id',
            field=models.ForeignKey(default='Gaza Blood Center', on_delete=django.db.models.deletion.DO_NOTHING, to='api.BloodCenter'),
            preserve_default=False,
        ),
    ]
