# Generated by Django 3.0.3 on 2020-04-22 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('date', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='getname',
            unique_together={('date', 'name')},
        ),
    ]
