# Generated by Django 3.0.3 on 2020-04-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200422_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='admin_id',
            new_name='user_id',
        ),
        migrations.DeleteModel(
            name='GetName',
        ),
    ]
