# Generated by Django 3.0.3 on 2020-05-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donor_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
    ]
