# Generated by Django 3.0.3 on 2020-05-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_donor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='phone_num',
        ),
    ]
