# Generated by Django 3.0.3 on 2020-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')]),
        ),
    ]
